package com.example.Curriculum.utils;

public enum Permission {
	SAVE_ADMINISTRATOR,
	READ_ADMINISTRATOR,
	UPDATE_ADMINISTRATOR,
	DELETE_ADMINISTRATOR,
	READ_CUSTOMER,
	SAVE_CUSTOMER,
	UPDATE_CUSTOMER
}
